In [1]:
x = [2, 3, 5, 7, 11]

In [2]:
sum(x)

28

In [3]:
mean(x)

NameError: name 'mean' is not defined

In [4]:
log(x)

NameError: name 'log' is not defined

In [5]:
x * 2

[2, 3, 5, 7, 11, 2, 3, 5, 7, 11]

In [6]:
x

[2, 3, 5, 7, 11]

In [7]:
x * 2

[2, 3, 5, 7, 11, 2, 3, 5, 7, 11]

In [8]:
x + 1

TypeError: can only concatenate list (not "int") to list

In [9]:
import numpy

In [10]:
array

NameError: name 'array' is not defined

In [14]:
numpy.array

<function numpy.array>

In [12]:
from numpy import array

In [13]:
array

<function numpy.array>

In [15]:
import numpy as np

In [16]:
numpy.array

<function numpy.array>

In [17]:
np.array

<function numpy.array>

In [18]:
x

[2, 3, 5, 7, 11]

In [20]:
x = np.array(x)

In [21]:
type(x)

numpy.ndarray

In [22]:
x.sum()

28

In [23]:
x.mean()

5.6

In [24]:
x.std()

3.2

In [25]:
x.var()

10.24

In [26]:
np.mean

<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)>

In [27]:
np.mean(x)

5.6

In [28]:
x + 1

array([ 3,  4,  6,  8, 12])

In [29]:
x * 2

array([ 4,  6, 10, 14, 22])

In [34]:
np.mean((x - x.mean())**2)

10.24

In [35]:
x.var(ddof = 1)


12.8

## Create a relatively large array of random numbers

In [38]:
y = np.random.rand(1000000)

In [39]:
y

array([0.53532247, 0.62478016, 0.71392182, ..., 0.51714164, 0.91008716,
       0.96724555])

In [40]:
y_list = list(y)

array([0.1664833 , 0.19859361, 0.9048056 , ..., 0.12868518, 0.76685541,
       0.98863637])

In [43]:
sum(y_list)

499743.6955185562

In [44]:
y.sum()

499743.6955185462

In [45]:
%timeit sum(y_list)

42.2 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [46]:
%timeit y.sum()

208 µs ± 5.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [47]:
y_list_speed = %timeit -o sum(y_list)

43 ms ± 740 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
y_list_speed.average

0.04296300998539664

In [49]:
y_np_speed = %timeit -o y.sum()

200 µs ± 2.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [51]:
y_np_speed.average

0.00020045595899656683

In [52]:
y_list_speed.average / y_np_speed.average

214.32642960807397

In [53]:
y

array([0.53532247, 0.62478016, 0.71392182, ..., 0.51714164, 0.91008716,
       0.96724555])

In [54]:
y[10:20]

array([0.12023452, 0.91299106, 0.44434886, 0.07925862, 0.26871955,
       0.51143901, 0.44722724, 0.31249016, 0.02304778, 0.77930189])

In [55]:
y[-10:]

array([0.75607042, 0.78510633, 0.88928695, 0.76219898, 0.18438439,
       0.36130085, 0.31535339, 0.51714164, 0.91008716, 0.96724555])

In [56]:
y[10:100]

array([0.12023452, 0.91299106, 0.44434886, 0.07925862, 0.26871955,
       0.51143901, 0.44722724, 0.31249016, 0.02304778, 0.77930189,
       0.64927932, 0.36929895, 0.98486807, 0.96743513, 0.32840113,
       0.49223581, 0.639132  , 0.23828939, 0.14915077, 0.11169451,
       0.92571653, 0.44709184, 0.29426721, 0.11048416, 0.75593411,
       0.73936292, 0.11262593, 0.41620466, 0.49220429, 0.67074134,
       0.75890153, 0.11355313, 0.74696083, 0.19364918, 0.97723467,
       0.70778411, 0.56259765, 0.91913005, 0.97775839, 0.72998922,
       0.16418358, 0.30348817, 0.02029273, 0.71174678, 0.24718189,
       0.59624024, 0.49207166, 0.84614184, 0.33636283, 0.01032016,
       0.69073708, 0.55700722, 0.21118737, 0.33406267, 0.34863878,
       0.83049821, 0.51780779, 0.89927337, 0.69773691, 0.53427117,
       0.85853734, 0.29820887, 0.33472243, 0.81750488, 0.19188712,
       0.6795856 , 0.53234045, 0.37136536, 0.73405134, 0.27597714,
       0.44067821, 0.02686935, 0.67756539, 0.27721502, 0.13425

In [58]:
y[10:1000:100]

array([0.12023452, 0.474179  , 0.33313551, 0.97572493, 0.1105951 ,
       0.43294659, 0.7570031 , 0.8239363 , 0.38538246, 0.54792539])

## n-d arrays

In [59]:
z = np.random.rand(10, 5)

In [60]:
z

array([[0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892],
       [0.69587382, 0.72156132, 0.24482982, 0.14500222, 0.29689609],
       [0.95994747, 0.90131929, 0.18864549, 0.45452013, 0.14908857],
       [0.41989459, 0.29978012, 0.69718132, 0.00656281, 0.72837697],
       [0.97566298, 0.40557653, 0.69286419, 0.10751993, 0.89744416],
       [0.91542196, 0.56229601, 0.8756743 , 0.56914041, 0.34527878],
       [0.02112053, 0.97580197, 0.88866146, 0.00353037, 0.70523286],
       [0.76676476, 0.43718269, 0.70937698, 0.22787457, 0.002344  ],
       [0.92724764, 0.98329569, 0.39944288, 0.59417668, 0.36817057],
       [0.52560971, 0.24749824, 0.2743726 , 0.27846127, 0.38207105]])

In [61]:
y_list_speed

<TimeitResult : 43 ms ± 740 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)>

In [62]:
z.shape

(10, 5)

In [63]:
y.shape

(1000000,)

In [64]:
z.size

50

In [67]:
np.random.rand(3, 5, 2)

array([[[0.46366033, 0.30845843],
        [0.31384354, 0.71570679],
        [0.51613342, 0.88280241],
        [0.72773841, 0.56437644],
        [0.69935145, 0.36540142]],

       [[0.66302993, 0.68791549],
        [0.84828002, 0.25526247],
        [0.574244  , 0.19587146],
        [0.11226797, 0.54952165],
        [0.80897478, 0.60268497]],

       [[0.02825765, 0.18261019],
        [0.84902599, 0.75953225],
        [0.57534875, 0.2612554 ],
        [0.13904935, 0.706742  ],
        [0.11471377, 0.87072596]]])

In [68]:
z

array([[0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892],
       [0.69587382, 0.72156132, 0.24482982, 0.14500222, 0.29689609],
       [0.95994747, 0.90131929, 0.18864549, 0.45452013, 0.14908857],
       [0.41989459, 0.29978012, 0.69718132, 0.00656281, 0.72837697],
       [0.97566298, 0.40557653, 0.69286419, 0.10751993, 0.89744416],
       [0.91542196, 0.56229601, 0.8756743 , 0.56914041, 0.34527878],
       [0.02112053, 0.97580197, 0.88866146, 0.00353037, 0.70523286],
       [0.76676476, 0.43718269, 0.70937698, 0.22787457, 0.002344  ],
       [0.92724764, 0.98329569, 0.39944288, 0.59417668, 0.36817057],
       [0.52560971, 0.24749824, 0.2743726 , 0.27846127, 0.38207105]])

In [69]:
z[0]

array([0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892])

In [71]:
z[:,0]


array([0.53706316, 0.69587382, 0.95994747, 0.41989459, 0.97566298,
       0.91542196, 0.02112053, 0.76676476, 0.92724764, 0.52560971])

In [72]:
z[0,:]

array([0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892])

In [73]:
np.sort(z)

array([[0.24772018, 0.29325182, 0.31776892, 0.36035796, 0.53706316],
       [0.14500222, 0.24482982, 0.29689609, 0.69587382, 0.72156132],
       [0.14908857, 0.18864549, 0.45452013, 0.90131929, 0.95994747],
       [0.00656281, 0.29978012, 0.41989459, 0.69718132, 0.72837697],
       [0.10751993, 0.40557653, 0.69286419, 0.89744416, 0.97566298],
       [0.34527878, 0.56229601, 0.56914041, 0.8756743 , 0.91542196],
       [0.00353037, 0.02112053, 0.70523286, 0.88866146, 0.97580197],
       [0.002344  , 0.22787457, 0.43718269, 0.70937698, 0.76676476],
       [0.36817057, 0.39944288, 0.59417668, 0.92724764, 0.98329569],
       [0.24749824, 0.2743726 , 0.27846127, 0.38207105, 0.52560971]])

In [74]:
z

array([[0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892],
       [0.69587382, 0.72156132, 0.24482982, 0.14500222, 0.29689609],
       [0.95994747, 0.90131929, 0.18864549, 0.45452013, 0.14908857],
       [0.41989459, 0.29978012, 0.69718132, 0.00656281, 0.72837697],
       [0.97566298, 0.40557653, 0.69286419, 0.10751993, 0.89744416],
       [0.91542196, 0.56229601, 0.8756743 , 0.56914041, 0.34527878],
       [0.02112053, 0.97580197, 0.88866146, 0.00353037, 0.70523286],
       [0.76676476, 0.43718269, 0.70937698, 0.22787457, 0.002344  ],
       [0.92724764, 0.98329569, 0.39944288, 0.59417668, 0.36817057],
       [0.52560971, 0.24749824, 0.2743726 , 0.27846127, 0.38207105]])

In [78]:
?np.sort

In [84]:
np.sort(z, 0)

array([[0.02112053, 0.24749824, 0.18864549, 0.00353037, 0.002344  ],
       [0.41989459, 0.29325182, 0.24482982, 0.00656281, 0.14908857],
       [0.52560971, 0.29978012, 0.24772018, 0.10751993, 0.29689609],
       [0.53706316, 0.40557653, 0.2743726 , 0.14500222, 0.31776892],
       [0.69587382, 0.43718269, 0.39944288, 0.22787457, 0.34527878],
       [0.76676476, 0.56229601, 0.69286419, 0.27846127, 0.36817057],
       [0.91542196, 0.72156132, 0.69718132, 0.36035796, 0.38207105],
       [0.92724764, 0.90131929, 0.70937698, 0.45452013, 0.70523286],
       [0.95994747, 0.97580197, 0.8756743 , 0.56914041, 0.72837697],
       [0.97566298, 0.98329569, 0.88866146, 0.59417668, 0.89744416]])

In [85]:
np.flipud(np.sort(z, 0))

array([[0.97566298, 0.98329569, 0.88866146, 0.59417668, 0.89744416],
       [0.95994747, 0.97580197, 0.8756743 , 0.56914041, 0.72837697],
       [0.92724764, 0.90131929, 0.70937698, 0.45452013, 0.70523286],
       [0.91542196, 0.72156132, 0.69718132, 0.36035796, 0.38207105],
       [0.76676476, 0.56229601, 0.69286419, 0.27846127, 0.36817057],
       [0.69587382, 0.43718269, 0.39944288, 0.22787457, 0.34527878],
       [0.53706316, 0.40557653, 0.2743726 , 0.14500222, 0.31776892],
       [0.52560971, 0.29978012, 0.24772018, 0.10751993, 0.29689609],
       [0.41989459, 0.29325182, 0.24482982, 0.00656281, 0.14908857],
       [0.02112053, 0.24749824, 0.18864549, 0.00353037, 0.002344  ]])

In [86]:
z

array([[0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892],
       [0.69587382, 0.72156132, 0.24482982, 0.14500222, 0.29689609],
       [0.95994747, 0.90131929, 0.18864549, 0.45452013, 0.14908857],
       [0.41989459, 0.29978012, 0.69718132, 0.00656281, 0.72837697],
       [0.97566298, 0.40557653, 0.69286419, 0.10751993, 0.89744416],
       [0.91542196, 0.56229601, 0.8756743 , 0.56914041, 0.34527878],
       [0.02112053, 0.97580197, 0.88866146, 0.00353037, 0.70523286],
       [0.76676476, 0.43718269, 0.70937698, 0.22787457, 0.002344  ],
       [0.92724764, 0.98329569, 0.39944288, 0.59417668, 0.36817057],
       [0.52560971, 0.24749824, 0.2743726 , 0.27846127, 0.38207105]])

In [88]:
z.reshape((2, 25))

array([[0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892,
        0.69587382, 0.72156132, 0.24482982, 0.14500222, 0.29689609,
        0.95994747, 0.90131929, 0.18864549, 0.45452013, 0.14908857,
        0.41989459, 0.29978012, 0.69718132, 0.00656281, 0.72837697,
        0.97566298, 0.40557653, 0.69286419, 0.10751993, 0.89744416],
       [0.91542196, 0.56229601, 0.8756743 , 0.56914041, 0.34527878,
        0.02112053, 0.97580197, 0.88866146, 0.00353037, 0.70523286,
        0.76676476, 0.43718269, 0.70937698, 0.22787457, 0.002344  ,
        0.92724764, 0.98329569, 0.39944288, 0.59417668, 0.36817057,
        0.52560971, 0.24749824, 0.2743726 , 0.27846127, 0.38207105]])

In [89]:
z.reshape(2, 25)

array([[0.53706316, 0.29325182, 0.24772018, 0.36035796, 0.31776892,
        0.69587382, 0.72156132, 0.24482982, 0.14500222, 0.29689609,
        0.95994747, 0.90131929, 0.18864549, 0.45452013, 0.14908857,
        0.41989459, 0.29978012, 0.69718132, 0.00656281, 0.72837697,
        0.97566298, 0.40557653, 0.69286419, 0.10751993, 0.89744416],
       [0.91542196, 0.56229601, 0.8756743 , 0.56914041, 0.34527878,
        0.02112053, 0.97580197, 0.88866146, 0.00353037, 0.70523286,
        0.76676476, 0.43718269, 0.70937698, 0.22787457, 0.002344  ,
        0.92724764, 0.98329569, 0.39944288, 0.59417668, 0.36817057,
        0.52560971, 0.24749824, 0.2743726 , 0.27846127, 0.38207105]])

In [90]:
z.T

array([[0.53706316, 0.69587382, 0.95994747, 0.41989459, 0.97566298,
        0.91542196, 0.02112053, 0.76676476, 0.92724764, 0.52560971],
       [0.29325182, 0.72156132, 0.90131929, 0.29978012, 0.40557653,
        0.56229601, 0.97580197, 0.43718269, 0.98329569, 0.24749824],
       [0.24772018, 0.24482982, 0.18864549, 0.69718132, 0.69286419,
        0.8756743 , 0.88866146, 0.70937698, 0.39944288, 0.2743726 ],
       [0.36035796, 0.14500222, 0.45452013, 0.00656281, 0.10751993,
        0.56914041, 0.00353037, 0.22787457, 0.59417668, 0.27846127],
       [0.31776892, 0.29689609, 0.14908857, 0.72837697, 0.89744416,
        0.34527878, 0.70523286, 0.002344  , 0.36817057, 0.38207105]])

In [91]:
a = np.random.rand(10)
b = np.random.rand(10)

In [92]:
a


array([0.23808495, 0.01272569, 0.59578701, 0.56963331, 0.93088514,
       0.47892383, 0.36862669, 0.02072053, 0.37824488, 0.81251777])

In [93]:
b

array([0.00906968, 0.76150315, 0.63864534, 0.78479886, 0.98223699,
       0.99735408, 0.20399438, 0.03279313, 0.44235476, 0.75386956])

In [95]:
(a * b).sum()

3.087128735283028

In [96]:
np.dot(a, b)

3.087128735283028

In [97]:
A = np.random.rand(10, 5)
B = np.random.rand(5, 2)

In [98]:
np.dot(A, B)

array([[1.02415128, 1.40124779],
       [1.26518703, 1.67258113],
       [0.90192443, 1.21601149],
       [1.33468759, 1.6831268 ],
       [0.85635421, 0.8496804 ],
       [0.52498641, 1.13705805],
       [0.92013838, 1.64163331],
       [0.76097697, 0.71973847],
       [1.20262428, 1.30484426],
       [0.61436643, 0.90470448]])

In [99]:
A * B 

ValueError: operands could not be broadcast together with shapes (10,5) (5,2) 

In [100]:
A @ B

array([[1.02415128, 1.40124779],
       [1.26518703, 1.67258113],
       [0.90192443, 1.21601149],
       [1.33468759, 1.6831268 ],
       [0.85635421, 0.8496804 ],
       [0.52498641, 1.13705805],
       [0.92013838, 1.64163331],
       [0.76097697, 0.71973847],
       [1.20262428, 1.30484426],
       [0.61436643, 0.90470448]])

In [101]:
A


array([[0.28074528, 0.53976549, 0.33122515, 0.81431308, 0.96925479],
       [0.9114208 , 0.81872798, 0.99080492, 0.28154416, 0.00934275],
       [0.85444585, 0.55555173, 0.28373469, 0.37334946, 0.30053204],
       [0.58043689, 0.78997886, 0.28445294, 0.92062644, 0.7550682 ],
       [0.09567804, 0.63617051, 0.24305186, 0.39432109, 0.60262446],
       [0.71844624, 0.17280592, 0.71893993, 0.10376162, 0.82064729],
       [0.49792567, 0.30909124, 0.63783   , 0.81714898, 0.89840329],
       [0.15657874, 0.63011336, 0.47259057, 0.0723257 , 0.39644084],
       [0.40633864, 0.86339471, 0.48547713, 0.46336981, 0.51868261],
       [0.47002452, 0.38024479, 0.52578218, 0.08331032, 0.71206206]])

In [103]:
np.sort(A, axis=0)

array([[0.09567804, 0.17280592, 0.24305186, 0.0723257 , 0.00934275],
       [0.15657874, 0.30909124, 0.28373469, 0.08331032, 0.30053204],
       [0.28074528, 0.38024479, 0.28445294, 0.10376162, 0.39644084],
       [0.40633864, 0.53976549, 0.33122515, 0.28154416, 0.51868261],
       [0.47002452, 0.55555173, 0.47259057, 0.37334946, 0.60262446],
       [0.49792567, 0.63011336, 0.48547713, 0.39432109, 0.71206206],
       [0.58043689, 0.63617051, 0.52578218, 0.46336981, 0.7550682 ],
       [0.71844624, 0.78997886, 0.63783   , 0.81431308, 0.82064729],
       [0.85444585, 0.81872798, 0.71893993, 0.81714898, 0.89840329],
       [0.9114208 , 0.86339471, 0.99080492, 0.92062644, 0.96925479]])

In [105]:
pwd

'/home/andrews/gitdev/misc/py4ds/notebooks/notes'

In [106]:
ls

data_visualization.ipynb           numba_stuff.ipynb
introduction_to_collections.ipynb  parallel_execution.ipynb
introduction_to_data_types.ipynb   parallel_with_joblib.ipynb
introduction_to_numpy.ipynb        rpy2.ipynb
introduction_to_pandas.ipynb       rpy_stuff.ipynb
intro_programming.ipynb            Untitled1.ipynb
intro_to_numpy.ipynb               Untitled2.ipynb
intro_to_pandas.ipynb              Untitled.ipynb
jit_with_numba.ipynb               using_r_in_python.ipynb
